</tbody></table>
<div className="mt-4 text-[9pt] text-[#cc0000]">2nd reattempt cannot be undertaken on the same date as the initial and 1st reattempt. (see Instructions to Students) The last date of this observation is to match the date for this assessment on the assessment outcome page.</div>
</div>

</div>


<div className="page">
  <InnerHeader />
  <div className="bg-[#dae3f3] py-2 px-3 mb-6 w-full flex-shrink-0">
    <h1 className="text-[14pt] font-bold text-black text-left m-0 p-0">Practical Assessment Task 4</h1>
    <div className="text-[10pt] text-black text-left m-0 p-0 mt-1">Install 4 New Pits</div>
  </div>
  <div className="mb-4 break-inside-avoid"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Practical Assessment Task 4 - Performance Criteria Mapping")}Practical Assessment Task 4 - Performance Criteria Mapping</h3>
<table className="w-full border-collapse border border-black text-[9pt]">
<thead><tr><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Performance Criteria</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Tick Completed</th></tr></thead>
<tbody><tr><td colSpan={2} className="border border-black p-2 font-bold bg-gray-100">Performance Criteria assessed in this task – ICTCBL334</td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.1 Obtain construction design plan from appropriate personnel and determine and obtain type of underground enclosure specified</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_1_1': compRecord['pa4_pc_1_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_1_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.2 Arrange access to site according to required enterprise procedure</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_1_2': compRecord['pa4_pc_1_2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_1_2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.3 Inform appropriate personnel of existing and potential worksite hazards</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_1_3': compRecord['pa4_pc_1_3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_1_3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.4 Verify location of proposed installation according to appropriate plans obtained from authorised personnel</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_1_4': compRecord['pa4_pc_1_4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_1_4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.5 Obtain information about location of other services from relevant authorities</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_1_5': compRecord['pa4_pc_1_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_1_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.6 Organise plant, tools and equipment for given work and safe work practice</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_1_6': compRecord['pa4_pc_1_6'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_1_6'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.7 Place recognised barriers during construction according to safety and enterprise requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_1_7': compRecord['pa4_pc_1_7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_1_7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.1 Excavate site, maintaining stability and allowing ease of access</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_2_1': compRecord['pa4_pc_2_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_2_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.2 Install enclosure or pit according to design specifications, and work health and safety (WHS) and environmental requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_2_2': compRecord['pa4_pc_2_2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_2_2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.3 Install conduit according to specifications and manufacturer requirements, ensuring internal surface from impediments and sharp edges for cable hauling</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_2_3': compRecord['pa4_pc_2_3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_2_3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.4 Seal conduit entry into enclosure against foreign matter</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_2_4': compRecord['pa4_pc_2_4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_2_4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.5 Install cable support structure and access facilities in pits according to specifications</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_2_5': compRecord['pa4_pc_2_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_2_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.1 Complete backfill safely using suitable soil and materials that ensure conduit protection</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_3_1': compRecord['pa4_pc_3_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_3_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.3 Restore site according to requirements of enterprise or approving authority and customer satisfaction</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_3_3': compRecord['pa4_pc_3_3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_3_3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.4 Complete reports on installation and design amendments accurately and file promptly according to requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_3_4': compRecord['pa4_pc_3_4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_3_4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.5 Notify appropriate personnel of job completion and obtain sign-off</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pc_3_5': compRecord['pa4_pc_3_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pc_3_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
</tbody></table></div>

  <PageFooter n={28} />
</div>


<div className="page">
  <InnerHeader />
  <div className="mb-4 break-inside-avoid"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Practical Assessment Task 4 - Performance Evidence Mapping")}Practical Assessment Task 4 - Performance Evidence Mapping</h3>
<table className="w-full border-collapse border border-black text-[9pt]">
<thead><tr><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Performance Evidence</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Tick Completed</th></tr></thead>
<tbody><tr><td colSpan={2} className="border border-black p-2 font-bold bg-gray-100">Performance Evidence assessed in this task-ICTCBL334</td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE1. interpret and apply design plans and prepare for construction</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pe_pe1': compRecord['pa4_pe_pe1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pe_pe1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE2. use specialised hand or power tools and equipment normally used for excavation, pipe, pit and conduit installation and site restoration, safely</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pe_pe2': compRecord['pa4_pe_pe2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pe_pe2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE3. place sand bed/foundation of suitable material prior to installing pit</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pe_pe3': compRecord['pa4_pe_pe3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pe_pe3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE4. connect conduits to pit according to standard specifications</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pe_pe4': compRecord['pa4_pe_pe4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pe_pe4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE5. install pit accessories such as support structures and gaskets according to requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pe_pe5': compRecord['pa4_pe_pe5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pe_pe5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE7. apply related work health and safety (WHS) requirements and work practices associated with excavation, enclosure installation and site restoration.</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_pe_pe7': compRecord['pa4_pe_pe7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_pe_pe7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
</tbody></table></div>

  <PageFooter n={29} />
</div>


<div className="page">
  <InnerHeader />
  <div className="bg-[#dae3f3] py-2 px-3 mb-6 w-full flex-shrink-0">
    <h1 className="text-[14pt] font-bold text-black text-left m-0 p-0">Practical Assessment Task 4</h1>
    <div className="text-[10pt] text-black text-left m-0 p-0 mt-1">Install 4 New Pits</div>
  </div>
  <div className="mb-4"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Assessment Task Description")}Assessment Task Description</h3><p className="whitespace-pre-wrap">For this assessment, you are working as a telco technician. You have been assigned a task as part of a team by your supervisor to install 4 new pits in preparation for jointing. You will be required set up all equipment, excavate the site, shore up the excavation, install one of the pits, install the connecting conduits to the adjacent pits, install a joint support bar and reinstate the site and prove the conduit and install rope in preparation for hauling.<br/><br/>Prior to commencing the task, you are required to assess the work site and complete a Job Safety Analysis (JSA) to capture and address hazards, unwanted events, and potential risks for the job.</p></div>
<div className="mb-4"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Resources Required")}Resources Required</h3><p className="whitespace-pre-wrap">• Learners Guide<br/>• Student Assessment Pack<br/>• Blue or Black Pen<br/>• WHS/OHS Acts/Regulations as applicable to the state of delivery<br/>• Codes of practice<br/>    ◦ How to manage work health and safety risks<br/>    ◦ Managing the work environment and facilities<br/>    ◦ Managing risks of plant in the workplace<br/>    ◦ Managing noise preventing hearing loss work<br/>    ◦ Managing the risk of falls at workplaces<br/>• Workplace procedure 01687W01 Working at Telstra Manholes and Pits<br/>• JSA-Included in this assessment pack<br/>• Installed #6 pit<br/>• #6 Pits x1<br/>• Manhole guards*<br/>• Pit keys x2*<br/>• Gas detector*<br/>• Gas action chart<br/>• Shovel<br/>• Shoring boards<br/>• Conduit rodder<br/>• Hauling rope*<br/>• Sand scoop*<br/>• Conduit cleaning brush*<br/>• Conduits slug*<br/>• 50mm white UPV Conduit x 2 metres*<br/>• 50mm PVC Bush x 2*<br/>• PVC Pipe adhesive and primer*<br/>• Fibreglass joint support bar x 0.5metres<br/>• 10mm paintbrush*<br/>• Hole saw 66mm*<br/>• Hack saw*<br/>• Deburring tool*<br/>• Retro reflective vest*<br/>• Gloves*<br/>• Hard Hat*<br/>• Safety glasses*<br/><br/>Manufacturers specifications and operating instructions for all tools & equipment specified with a *</p></div>

  <PageFooter n={30} />
</div>


<div className="page">
  <InnerHeader />
  <div className="mb-4"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Assessment Instructions")}Assessment Instructions</h3><p className="whitespace-pre-wrap">Complete the following activities:<br/>1. Ensure that all tasks follow WHS/OHS requirements.<br/>2. Refer to tool/equipment instructions prior to use.<br/>3. Refer to the completed JSA.<br/>4. Ensure gas detector is on.<br/>5. Set up all equipment.<br/>6. Excavate the site.<br/>7. Shore up the excavation.<br/>8. Install one of the pits.<br/>9. Install the connecting conduits to the adjacent pits.<br/>10. Backfill site.<br/>11. Rod conduit.<br/>12. Attach hauling line and draw through conduit.<br/>13. Attach cleaning brush and clean debris.<br/>14. Prove conduit with appropriate slug.<br/>15. Leave hauling line in conduit.<br/>16. Install a joint support bar in the pit.<br/>17. Fit the pit gasket and pit lid.<br/>18. Submit your completed work for inspection.</p></div>
<div className="mb-6 flex flex-col items-center"><img src="/assets/question-15/task4.png" alt="Pit installation plan" className="max-w-[400px] max-h-[250px] object-contain border border-gray-300" /><div className="text-center italic text-sm mt-2 text-gray-600">Pit installation plan</div></div>

  <PageFooter n={31} />
</div>


<div className="page">
  <InnerHeader />
  <div className="mb-4 break-inside-avoid"><h1 className="text-[14pt] font-bold bg-[#c0cddf] py-2 px-3 rounded-sm border border-black text-left mb-4 mt-2">
Practical Assessment Task 4 - Checklist</h1>
<table className="w-full border-collapse border border-black text-[9pt]">
<thead><tr><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Did the student:</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Yes</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">No</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Comments</th></tr></thead>
<tbody><tr><td colSpan={4} className="border border-black p-2 font-medium">Student's name: <span className="font-bold ml-2">{studentName}</span></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Ensure that all tasks will follow all applicable WHS/OHS requirements and procedures in appropriate Codes of Practice</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_1': compRecord['pa4_cl_1'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_1'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_1': compRecord['pa4_cl_1'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_1'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_1_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_1_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Refer to all tool/equipment instructions/manufacturers guidelines prior to use.</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_2': compRecord['pa4_cl_2'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_2'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_2': compRecord['pa4_cl_2'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_2'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_2_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_2_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Refer to the completed JSA for the task</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_3': compRecord['pa4_cl_3'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_3'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_3': compRecord['pa4_cl_3'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_3'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_3_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_3_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Ensure gas detector is on and carried on your person</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_4': compRecord['pa4_cl_4'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_4'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_4': compRecord['pa4_cl_4'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_4'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_4_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_4_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Set up all equipment</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_5': compRecord['pa4_cl_5'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_5'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_5': compRecord['pa4_cl_5'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_5'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_5_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_5_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Excavate the site</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_6': compRecord['pa4_cl_6'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_6'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_6': compRecord['pa4_cl_6'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_6'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_6_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_6_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Shore up the excavation</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_7': compRecord['pa4_cl_7'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_7'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_7': compRecord['pa4_cl_7'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_7'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_7_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_7_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Install one of the pits</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_8': compRecord['pa4_cl_8'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_8'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_8': compRecord['pa4_cl_8'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_8'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_8_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_8_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Install the connecting conduits to the adjacent pits</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_9': compRecord['pa4_cl_9'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_9'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_9': compRecord['pa4_cl_9'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_9'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_9_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_9_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Backfill site</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_10': compRecord['pa4_cl_10'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_10'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_10': compRecord['pa4_cl_10'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_10'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_10_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_10_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Rod conduit</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_11': compRecord['pa4_cl_11'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_11'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_11': compRecord['pa4_cl_11'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_11'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_11_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_11_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Attach hauling line and draw through conduit</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_12': compRecord['pa4_cl_12'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_12'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_12': compRecord['pa4_cl_12'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_12'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_12_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_12_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Attach cleaning brush to hauling line and clean debris from conduit</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_13': compRecord['pa4_cl_13'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_13'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_13': compRecord['pa4_cl_13'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_13'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_13_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_13_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Prove conduit with appropriate size slug</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_14': compRecord['pa4_cl_14'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_14'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_14': compRecord['pa4_cl_14'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_14'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_14_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_14_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Leave hauling line in conduit</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_15': compRecord['pa4_cl_15'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_15'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_15': compRecord['pa4_cl_15'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_15'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_15_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_15_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Submit your completed work to your supervisor (assessor) for inspection</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_16': compRecord['pa4_cl_16'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_16'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_16': compRecord['pa4_cl_16'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_cl_16'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_cl_16_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_cl_16_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Task Outcome:</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_outcome': compRecord['pa4_outcome'] === 'Satisfactory' ? '' : 'Satisfactory' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_outcome'] === 'Satisfactory' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span>Satisfactory</span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa4_outcome': compRecord['pa4_outcome'] === 'Not Satisfactory' ? '' : 'Not Satisfactory' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa4_outcome'] === 'Not Satisfactory' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span>Not Satisfactory</span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_outcome_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_outcome_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Assessor signature</td><td colSpan={3} className="border border-black p-2 text-center align-middle"><div onClick={() => !isStudent && openSigModal('pa4_assessor_sig', 'comp')} className="w-full border-b border-black border-dashed min-h-[20px] cursor-pointer flex items-center justify-center">{compRecord['pa4_assessor_sig'] ? <img src={compRecord['pa4_assessor_sig']} className="max-h-[25px] max-w-[100px] object-contain inline-block" /> : <span className="text-[10px] text-slate-400 italic no-print">{isStudent ? '' : 'Click to sign'}</span>}</div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Assessor name</td><td colSpan={3} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_assessor_name'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_assessor_name': e.target.value })} readOnly={isStudent} placeholder="Enter assessor name..." /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Date</td><td colSpan={3} className="border border-black p-2 text-center align-middle"><input type="date" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa4_date'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa4_date': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
</tbody></table></div>

    <div className="mt-8" style={{ pageBreakInside: 'avoid' }}>
      <h3 style={{ fontWeight: 'bold', fontSize: '11pt', marginBottom: '12px' }}>Comments/Feedback to Participant</h3>

      <table style={{ width: '100%', borderCollapse: 'collapse', border: '1.5px solid black', marginBottom: '20px' }}>
        <tbody>
          <tr>
            <td style={{ width: '60%', borderRight: '1.5px solid black', padding: '8px', verticalAlign: 'top' }}>
              <p style={{ margin: 0, lineHeight: '1.4', fontSize: '10pt' }}><span style={{ fontWeight: 'bold' }}>Student Declaration:</span> I declare that the work submitted is my own, and has not been copied or plagiarized from any person or source.</p>
            </td>
            <td style={{ width: '40%', padding: '8px 12px', position: 'relative', fontSize: '10pt' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', height: '100%', justifyContent: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Signature:</span>
                  <div
                    className="no-print"
                    onClick={() => openSigModal('student_signature', 'comp')}
                    style={{ borderBottom: '1.5px solid black', flex: 1, minHeight: '24px', cursor: 'pointer', position: 'relative' }}
                  >
                    {answers.student_signature_url ? (
                      <img src={answers.student_signature_url} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    ) : (
                      <span style={{ fontSize: '9px', color: '#888' }}>{isStudent ? '' : 'Click to sign'}</span>
                    )}
                  </div>
                  <div className="hidden print:block" style={{ borderBottom: '1.5px solid black', flex: 1, height: '20px', position: 'relative' }}>
                    {answers.student_signature_url && (
                      <img src={answers.student_signature_url} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    )}
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Date:</span>
                  <span style={{ borderBottom: '1.5px solid black', flex: 1, display: 'inline-block', height: '20px', paddingLeft: '4px', fontWeight: 'bold' }}>
                    {formatDisplayDate(submitDate || '')}
                  </span>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>

      <div style={{ border: '1.5px solid black', padding: '8px', minHeight: '120px', marginBottom: '20px' }}>
        <p style={{ fontWeight: 'bold', margin: '0 0 8px 0', fontSize: '10pt' }}>Assessor's Feedback:</p>
        <textarea
          className="no-print"
          style={{ width: '100%', minHeight: '90px', border: 'none', resize: 'vertical', fontFamily: "'Times New Roman', serif", fontSize: '10.5pt', padding: 0, outline: 'none', backgroundColor: 'transparent' }}
          placeholder="Assessor feedback..."
          value={compRecord['task5_feedback'] || ''}
          onChange={(e) => { if (!isStudent) setCompRecord({ ...compRecord, 'task5_feedback': e.target.value }) }}
          readOnly={isStudent}
        />
        <div className="hidden print:block" style={{ whiteSpace: 'pre-wrap', minHeight: '90px', fontSize: '10.5pt' }}>
          {compRecord['task5_feedback']}
        </div>
      </div>

      <div style={{ textAlign: 'center', marginBottom: '20px', fontWeight: 'bold', fontSize: '12.5pt' }}>
        Result:{' '}
        <span
          className={`relative inline-block mx-2 ${isStudent ? '' : 'cursor-pointer'}`}
          onClick={() => { if (!isStudent) setCompRecord({ ...compRecord, 'task5_result': 'S' }) }}
          style={{ padding: '4px' }}
        >
          Satisfactory (S)
          {compRecord['task5_result'] === 'S' && (
            <span style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', border: '2px solid red', borderRadius: '50%', width: '110%', height: '140%', pointerEvents: 'none' }}></span>
          )}
        </span>
        <span style={{ margin: '0 8px' }}>/</span>
        <span
          className={`relative inline-block mx-2 ${isStudent ? '' : 'cursor-pointer'}`}
          onClick={() => { if (!isStudent) setCompRecord({ ...compRecord, 'task5_result': 'NS' }) }}
          style={{ padding: '4px' }}
        >
          Not Satisfactory (NS)
          {compRecord['task5_result'] === 'NS' && (
            <span style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', border: '2px solid red', borderRadius: '50%', width: '110%', height: '140%', pointerEvents: 'none' }}></span>
          )}
        </span>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse', border: '1.5px solid black' }}>
        <tbody>
          <tr>
            <td style={{ width: '60%', borderRight: '1.5px solid black', padding: '8px', verticalAlign: 'top' }}>
              <p style={{ margin: 0, lineHeight: '1.4', fontSize: '10pt' }}><span style={{ fontWeight: 'bold' }}>Assessor:</span> I declare that I have conducted a fair, valid, reliable and flexible assessment with this student, and I have provided appropriate feedback.</p>
            </td>
            <td style={{ width: '40%', padding: '8px 12px', position: 'relative', fontSize: '10pt' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', height: '100%', justifyContent: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Signature:</span>
                  <div
                    className="no-print"
                    onClick={() => openSigModal('assessor_signature', 'comp')}
                    style={{ borderBottom: '1.5px solid black', flex: 1, minHeight: '24px', cursor: isStudent ? 'default' : 'pointer', position: 'relative' }}
                  >
                    {compRecord.assessor_signature ? (
                      <img src={compRecord.assessor_signature} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    ) : (
                      <span style={{ fontSize: '9px', color: '#888' }}>{isStudent ? '' : 'Click to sign'}</span>
                    )}
                  </div>
                  <div className="hidden print:block" style={{ borderBottom: '1.5px solid black', flex: 1, height: '20px', position: 'relative' }}>
                    {compRecord.assessor_signature && (
                      <img src={compRecord.assessor_signature} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    )}
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Date:</span>
                  <span className="no-print" style={{ borderBottom: '1.5px solid black', flex: 1, display: 'inline-block', height: '24px', position: 'relative' }}>
                    <input
                      type="date"
                      style={{ width: '100%', height: '100%', outline: 'none', border: 'none', background: 'transparent', fontFamily: "'Times New Roman', serif", fontSize: '10pt', margin: 0, padding: '0 0 0 4px', cursor: isStudent ? 'default' : 'pointer' }}
                      value={compRecord.assessment_date || ''}
                      onChange={(e) => { if (!isStudent) setCompRecord({ ...compRecord, assessment_date: e.target.value }) }}
                      readOnly={isStudent}
                    />
                  </span>
                  <span className="hidden print:inline-block" style={{ borderBottom: '1.5px solid black', flex: 1, height: '20px', paddingLeft: '4px' }}>
                    {compRecord.assessment_date ? formatDisplayDate(compRecord.assessment_date) : ''}
                  </span>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  
  <PageFooter n={32} />
</div>


<div className="page">
  <InnerHeader />
  <div className="bg-[#dae3f3] py-2 px-3 mb-6 w-full flex-shrink-0">
    <h1 className="text-[14pt] font-bold text-black text-left m-0 p-0">Practical Assessment Task 5</h1>
    <div className="text-[10pt] text-black text-left m-0 p-0 mt-1">Performance Criteria & Checklist</div>
  </div>
  <div className="mb-4 break-inside-avoid"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Practical Assessment Task 5 - Performance Criteria Mapping (ICTCBL249)")}Practical Assessment Task 5 - Performance Criteria Mapping (ICTCBL249)</h3>
<table className="w-full border-collapse border border-black text-[9pt]">
<thead><tr><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Performance Criteria</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Tick Completed</th></tr></thead>
<tbody><tr><td colSpan={2} className="border border-black p-2 font-bold bg-gray-100">Performance Criteria assessed in this task – ICTCBL249</td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.1 Arrange access to site according to required procedure</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_1_1': compRecord['pa5_pc_1_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_1_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.2 Inform appropriate personnel of identified hazards on worksite</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_1_2': compRecord['pa5_pc_1_2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_1_2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.3 Confirm hauling location of proposed cable according to appropriate plan specifications obtained from authorised personnel</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_1_3': compRecord['pa5_pc_1_3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_1_3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.4 Obtain information about proposed locations of other services from relevant authorities</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_1_4': compRecord['pa5_pc_1_4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_1_4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.5 Set up tools and equipment required for safe work practice according to enterprise guidelines</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_1_5': compRecord['pa5_pc_1_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_1_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.6 Check for dangerous gases and place guards around open manholes according to work health and safety (WHS) and environmental requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_1_6': compRecord['pa5_pc_1_6'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_1_6'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.1 InstaIl cable protection on pole for transition using approved hardware according to industry standards and asset owner requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_1': compRecord['pa5_pc_2_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.2 Connect conduit to pits or manholes as designed according to industry standards and asset owner requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_2': compRecord['pa5_pc_2_2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.3 Haule existing cables in a way that avoids cable damage</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_3': compRecord['pa5_pc_2_3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.4 Rodding techniques to prove that underground conduit is clear for hauling</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_4': compRecord['pa5_pc_2_4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.5 Attach cable to rope for hauling, lubricate cable as required and haul at correct tension, maintaining smooth passage between dispenser and hauler</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_5': compRecord['pa5_pc_2_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.5 Pull cable through conduit to facilitate aerial to underground transition/underground to aerial transition, as required</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_5': compRecord['pa5_pc_2_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.5 Retain sufficient cable length allowance for jointing and ensure cable is laid up and bent within bending radius tolerance for materials in underground enclosure</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_5': compRecord['pa5_pc_2_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.7 Cables according to enterprise requirements to ensure no sheath damage</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_7': compRecord['pa5_pc_2_7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.8 Attach ID tag for future identification</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_8': compRecord['pa5_pc_2_8'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_8'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.8 Clean the site to customer satisfaction and dispose of waste in an environmentally safe manner</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_8': compRecord['pa5_pc_2_8'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_8'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.9 Appropriate personnel about job completion and obtain sign-off</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa5_pc_2_9': compRecord['pa5_pc_2_9'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa5_pc_2_9'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
</tbody></table></div>

  <PageFooter n={33} />
</div>


<div className="page">
  <InnerHeader />
  <div className="mb-4 break-inside-avoid"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Practical Assessment Task 5 - Performance Evidence Mapping (ICTCBL249)")}Practical Assessment Task 5 - Performance Evidence Mapping (ICTCBL249)</h3>
<table className="w-full border-collapse border border-black text-[9pt]">
