<tr><td colSpan={2} className="border border-black p-2 font-bold bg-gray-100">Performance Criteria assessed in this task – ICTCBL329</td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.1 Access site according to required enterprise procedures</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_1': compRecord['pa3_pc_1_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.2 Verify cable installation requirements from plans and recognise constraints</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_2': compRecord['pa3_pc_1_2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.3 Identify from plans, correct duct to be hauled</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_3': compRecord['pa3_pc_1_3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.4 Inform appropriate personnel of existing and potential worksite hazards</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_4': compRecord['pa3_pc_1_4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.5 Obtain information about location of other services from relevant authorities</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_5': compRecord['pa3_pc_1_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.6 Select suitable tools, equipment, and protective equipment to meet required industry standards.</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_6': compRecord['pa3_pc_1_6'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_6'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.7 Check for dangerous gases and place guards around open manholes following work health and safety (WHS) and environmental requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_7': compRecord['pa3_pc_1_7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.8 Confirm correct duct/conduit to be utilised for hauling at site and access to intermediate manholes/pits along the hauling route</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_8': compRecord['pa3_pc_1_8'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_8'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">1.10 Set-up cable installation equipment according to manufacturer requirements and enterprise guidelines</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_1_10': compRecord['pa3_pc_1_10'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_1_10'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.1 Attach cable to hauling feeder according to manufacturer specifications</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_2_1': compRecord['pa3_pc_2_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_2_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.2 Employ cable slippers or rollers to ensure no sheath damage when hauling into and out of enclosures</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_2_2': compRecord['pa3_pc_2_2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_2_2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.5 Lubricate cable and haul evenly at correct tension to reduce risk of cable damage</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_2_5': compRecord['pa3_pc_2_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_2_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.5 Maintain sufficient cable length allowance for jointing and ensure cable is housed within bending radius tolerance for cable materials in an underground enclosure</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_3_5': compRecord['pa3_pc_3_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_3_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">2.7 Maintain cable and services separations in parallel runs and crossovers according to manufacturer and regulatory requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_2_7': compRecord['pa3_pc_2_7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_2_7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.1 Tag all cables to enable future identification</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_3_1': compRecord['pa3_pc_3_1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_3_1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.2.2 Seal cable ends according to enterprise requirements to prevent entrance of foreign material</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_3_2_2': compRecord['pa3_pc_3_2_2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_3_2_2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.3 Place cable on supports in enclosures to reduce damage to conductors and enable ease of access for maintenance</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_3_3': compRecord['pa3_pc_3_3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_3_3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.5 Complete installation reports and design amendments accurately, and file promptly according to customer requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_3_5': compRecord['pa3_pc_3_5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_3_5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.6 Reinstate site to customer satisfaction and dispose of waste in environmentally safe manner as required</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_3_6': compRecord['pa3_pc_3_6'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_3_6'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">3.7 Notify appropriate personnel and obtain sign-off</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pc_3_7': compRecord['pa3_pc_3_7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pc_3_7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
</tbody></table></div>

  <PageFooter n={23} />
</div>


<div className="page">
  <InnerHeader />
  <div className="mb-4 break-inside-avoid"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Practical Assessment Task 3 - Performance Evidence Mapping")}Practical Assessment Task 3 - Performance Evidence Mapping</h3>
<table className="w-full border-collapse border border-black text-[9pt]">
<thead><tr><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Performance Evidence</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Tick Completed</th></tr></thead>
<tbody><tr><td colSpan={2} className="border border-black p-2 font-bold bg-gray-100">Performance Evidence assessed in this task-ICTCBL249</td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE1. plan the works and prepare the site</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe1': compRecord['pa3_pe_pe1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE2. read and interpret drawings and designs to interpret installation requirements</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe2': compRecord['pa3_pe_pe2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE3. haul cable applying related work health and safety (WHS) requirements and work practices</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe3': compRecord['pa3_pe_pe3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE5. use cable dispensing equipment</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe5': compRecord['pa3_pe_pe5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE6. use specialised hand or power tools and equipment for hauling cable safely</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe6': compRecord['pa3_pe_pe6'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe6'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE7. test the installation, document, and escalate the test result</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe7': compRecord['pa3_pe_pe7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE8. prepare all reports and records to industry and enterprise standards.</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe8': compRecord['pa3_pe_pe8'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe8'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td colSpan={2} className="border border-black p-2 font-bold bg-gray-100">Performance Evidence assessed in this task-ICTCBL329</td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE1. use correct type of rope for cable hauling</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe1': compRecord['pa3_pe_pe1'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe1'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE2. use various rodding, roping and mandrel techniques as prior requirements to hauling cable</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe2': compRecord['pa3_pe_pe2'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe2'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE3. haul cable safely applying related work health and safety (WHS) requirements and work practices</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe3': compRecord['pa3_pe_pe3'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe3'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE4. restore site and complete documentation</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe4': compRecord['pa3_pe_pe4'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe4'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE5. use specialised hand or power tools and equipment for hauling cabling safely</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe5': compRecord['pa3_pe_pe5'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe5'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">PE7. comply with all related safety requirements and work practices.</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_pe_pe7': compRecord['pa3_pe_pe7'] === 'Completed' ? '' : 'Completed' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_pe_pe7'] === 'Completed' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td></tr>
</tbody></table></div>

  <PageFooter n={24} />
</div>


<div className="page">
  <InnerHeader />
  <div className="mb-4 break-inside-avoid"><h1 className="text-[14pt] font-bold bg-[#c0cddf] py-2 px-3 rounded-sm border border-black text-left mb-4 mt-2">
Practical Assessment Task 3 - Checklist</h1>
<table className="w-full border-collapse border border-black text-[9pt]">
<thead><tr><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Did the student:</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Yes</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">No</th><th className="border border-black bg-gray-200 p-2 text-center font-bold whitespace-pre-wrap">Comments</th></tr></thead>
<tbody><tr><td colSpan={4} className="border border-black p-2 font-medium">Student's name: <span className="font-bold ml-2">{studentName}</span></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Ensure that all tasks will follow all applicable WHS/OHS requirements and procedures in appropriate Codes of Practice</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_1': compRecord['pa3_cl_1'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_1'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_1': compRecord['pa3_cl_1'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_1'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_1_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_1_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Refer to all tool/equipment instructions/manufacturers guidelines prior to use.</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_2': compRecord['pa3_cl_2'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_2'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_2': compRecord['pa3_cl_2'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_2'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_2_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_2_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Refer to the completed JSA for the task</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_3': compRecord['pa3_cl_3'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_3'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_3': compRecord['pa3_cl_3'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_3'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_3_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_3_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Ensure gas detector is on and carried on your person</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_4': compRecord['pa3_cl_4'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_4'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_4': compRecord['pa3_cl_4'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_4'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_4_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_4_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Ensure cable guides/slippers are installed correctly</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_5': compRecord['pa3_cl_5'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_5'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_5': compRecord['pa3_cl_5'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_5'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_5_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_5_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Attach cable grip to cable and tape on</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_6': compRecord['pa3_cl_6'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_6'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_6': compRecord['pa3_cl_6'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_6'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_6_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_6_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Attach hauling rope to cable grip eye and tie off securely.</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_7': compRecord['pa3_cl_7'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_7'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_7': compRecord['pa3_cl_7'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_7'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_7_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_7_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Attach a new hauling rope to the cable grip eye</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_8': compRecord['pa3_cl_8'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_8'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_8': compRecord['pa3_cl_8'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_8'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_8_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_8_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Lubricate the cable</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_9': compRecord['pa3_cl_9'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_9'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_9': compRecord['pa3_cl_9'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_9'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_9_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_9_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Haul the cable ensuring hauling tension is not exceeded</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_10': compRecord['pa3_cl_10'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_10'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_10': compRecord['pa3_cl_10'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_10'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_10_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_10_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Ensure cable is cut with sufficient left in pits for jointing</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_11': compRecord['pa3_cl_11'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_11'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_11': compRecord['pa3_cl_11'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_11'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_11_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_11_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Flame brush cable end</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_12': compRecord['pa3_cl_12'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_12'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_12': compRecord['pa3_cl_12'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_12'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_12_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_12_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Fit endcap and shrink to seal cable</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_13': compRecord['pa3_cl_13'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_13'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_13': compRecord['pa3_cl_13'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_13'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_13_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_13_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Fit cable tags to both ends of cable</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_14': compRecord['pa3_cl_14'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_14'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_14': compRecord['pa3_cl_14'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_14'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_14_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_14_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Coil excess cable and secure to cable supports</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_15': compRecord['pa3_cl_15'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_15'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_15': compRecord['pa3_cl_15'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_15'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_15_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_15_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Test the continuity of the cable</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_16': compRecord['pa3_cl_16'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_16'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_16': compRecord['pa3_cl_16'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_16'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_16_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_16_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Close pits</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_17': compRecord['pa3_cl_17'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_17'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_17': compRecord['pa3_cl_17'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_17'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_17_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_17_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Ensure sufficient separation from other services in pits</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_18': compRecord['pa3_cl_18'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_18'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_18': compRecord['pa3_cl_18'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_18'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_18_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_18_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Restore site and clean and return all tools and equipment to the appropriate location</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_19': compRecord['pa3_cl_19'] === 'Yes' ? '' : 'Yes' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_19'] === 'Yes' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_19': compRecord['pa3_cl_19'] === 'No' ? '' : 'No' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_cl_19'] === 'No' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span></span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_cl_19_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_cl_19_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Task Outcome:</td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_outcome': compRecord['pa3_outcome'] === 'Satisfactory' ? '' : 'Satisfactory' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_outcome'] === 'Satisfactory' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span>Satisfactory</span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><div className="flex flex-col gap-1 items-center justify-center"><div className="flex gap-2 items-center cursor-pointer" onClick={() => !isStudent && setCompRecord({ ...compRecord, 'pa3_outcome': compRecord['pa3_outcome'] === 'Not Satisfactory' ? '' : 'Not Satisfactory' })}><div className="w-4 h-4 border border-black rounded-sm flex items-center justify-center bg-white">{compRecord['pa3_outcome'] === 'Not Satisfactory' && <span className="text-red-600 font-bold text-lg leading-none">✓</span>}</div><span>Not Satisfactory</span></div></div></td><td colSpan={1} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_outcome_comments'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_outcome_comments': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Assessor signature</td><td colSpan={3} className="border border-black p-2 text-center align-middle"><div onClick={() => !isStudent && openSigModal('pa3_assessor_sig', 'comp')} className="w-full border-b border-black border-dashed min-h-[20px] cursor-pointer flex items-center justify-center">{compRecord['pa3_assessor_sig'] ? <img src={compRecord['pa3_assessor_sig']} className="max-h-[25px] max-w-[100px] object-contain inline-block" /> : <span className="text-[10px] text-slate-400 italic no-print">{isStudent ? '' : 'Click to sign'}</span>}</div></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Assessor name</td><td colSpan={3} className="border border-black p-2 text-center align-middle"><input type="text" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_assessor_name'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_assessor_name': e.target.value })} readOnly={isStudent} placeholder="Enter assessor name..." /></td></tr>
<tr><td className="border border-black p-2 font-medium w-3/5">Date</td><td colSpan={3} className="border border-black p-2 text-center align-middle"><input type="date" className="w-full border-b border-black border-dashed min-h-[20px] bg-transparent text-center focus:outline-none" value={compRecord['pa3_date'] || ''} onChange={(e) => !isStudent && setCompRecord({ ...compRecord, 'pa3_date': e.target.value })} readOnly={isStudent} placeholder="" /></td></tr>
</tbody></table></div>

  <PageFooter n={25} />
</div>


<div className="page">
  <InnerHeader />
  <div className="bg-[#dae3f3] py-2 px-3 mb-6 w-full flex-shrink-0">
    <h1 className="text-[14pt] font-bold text-black text-left m-0 p-0">Practical Assessment Task 3</h1>
    <div className="text-[10pt] text-black text-left m-0 p-0 mt-1">Haul Cable</div>
  </div>
  <div className="mb-4"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Assessment Instructions")}Assessment Instructions</h3><p className="whitespace-pre-wrap">Complete the following activities:<br/>1. Ensure that all tasks will follow all applicable WHS/OHS requirements and procedures in appropriate Codes of Practice<br/>2. Refer to all tool/equipment instructions/manufacturers guidelines prior to use.<br/>3. Refer to the completed JSA for the task<br/>4. Ensure gas detector is on and carried on your person<br/>5. Attach cable grip to cable and tape on<br/>6. Ensure cable guides/slippers are installed correctly<br/>7. Attach hauling rope to cable grip eye and tie off securely.<br/>8. Attach a new hauling rope to the cable grip eye<br/>9. Lubricate the cable<br/>10. Haul the cable ensuring that you do not exceed the manufacturers hauling tension<br/>11. Ensure sufficient cable is left in pits for jointing and cut from drum.<br/>12. Flame brush cable end<br/>13. Fit endcap and shrink to seal cable<br/>14. Fit cable tags to both ends of cable<br/>15. Coil excess cable and secure to cable supports<br/>16. Ensure sufficient separation from other services in pits<br/>17. Test the continuity of the cable<br/>18. Close pits<br/>19. Restore site and clean and return all tools and equipment to the appropriate location<br/>20. Complete red line mark-up of plan showing completed work<br/>21. Complete project sign off sheet and get customer (assessor) approval<br/>22. Submit your completed work to your supervisor (assessor) for inspection</p></div>
<div className="mb-6 flex flex-col items-center"><img src="/assets/question-15/task3.png" alt="Hauling operation plan" className="max-w-[400px] max-h-[300px] object-contain border border-gray-300" /><div className="text-center italic text-sm mt-2 text-gray-600">Hauling operation plan</div></div>

  <PageFooter n={26} />
</div>


<div className="page">
  <InnerHeader />
  <div className="mb-6 flex flex-col items-center"><img src="/assets/question-15/task3b.png" alt="Hauling equipment setup" className="max-w-[400px] max-h-[300px] object-contain border border-gray-300" /><div className="text-center italic text-sm mt-2 text-gray-600">Hauling equipment setup</div></div>
<div className="mb-4"><h3 className="font-bold mb-2 flex items-center">{renderSectionIcon("Test Results")}Test Results</h3><p className="whitespace-pre-wrap">Record the test results for continuity and loop resistance.<br/>Loop resistance of 1st pair: ________ Ohms</p></div>

    <div className="mt-8" style={{ pageBreakInside: 'avoid' }}>
      <h3 style={{ fontWeight: 'bold', fontSize: '11pt', marginBottom: '12px' }}>Comments/Feedback to Participant</h3>

      <table style={{ width: '100%', borderCollapse: 'collapse', border: '1.5px solid black', marginBottom: '20px' }}>
        <tbody>
          <tr>
            <td style={{ width: '60%', borderRight: '1.5px solid black', padding: '8px', verticalAlign: 'top' }}>
              <p style={{ margin: 0, lineHeight: '1.4', fontSize: '10pt' }}><span style={{ fontWeight: 'bold' }}>Student Declaration:</span> I declare that the work submitted is my own, and has not been copied or plagiarized from any person or source.</p>
            </td>
            <td style={{ width: '40%', padding: '8px 12px', position: 'relative', fontSize: '10pt' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', height: '100%', justifyContent: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Signature:</span>
                  <div
                    className="no-print"
                    onClick={() => openSigModal('student_signature', 'comp')}
                    style={{ borderBottom: '1.5px solid black', flex: 1, minHeight: '24px', cursor: 'pointer', position: 'relative' }}
                  >
                    {answers.student_signature_url ? (
                      <img src={answers.student_signature_url} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    ) : (
                      <span style={{ fontSize: '9px', color: '#888' }}>{isStudent ? '' : 'Click to sign'}</span>
                    )}
                  </div>
                  <div className="hidden print:block" style={{ borderBottom: '1.5px solid black', flex: 1, height: '20px', position: 'relative' }}>
                    {answers.student_signature_url && (
                      <img src={answers.student_signature_url} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    )}
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Date:</span>
                  <span style={{ borderBottom: '1.5px solid black', flex: 1, display: 'inline-block', height: '20px', paddingLeft: '4px', fontWeight: 'bold' }}>
                    {formatDisplayDate(submitDate || '')}
                  </span>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>

      <div style={{ border: '1.5px solid black', padding: '8px', minHeight: '120px', marginBottom: '20px' }}>
        <p style={{ fontWeight: 'bold', margin: '0 0 8px 0', fontSize: '10pt' }}>Assessor's Feedback:</p>
        <textarea
          className="no-print"
          style={{ width: '100%', minHeight: '90px', border: 'none', resize: 'vertical', fontFamily: "'Times New Roman', serif", fontSize: '10.5pt', padding: 0, outline: 'none', backgroundColor: 'transparent' }}
          placeholder="Assessor feedback..."
          value={compRecord['task4_feedback'] || ''}
          onChange={(e) => { if (!isStudent) setCompRecord({ ...compRecord, 'task4_feedback': e.target.value }) }}
          readOnly={isStudent}
        />
        <div className="hidden print:block" style={{ whiteSpace: 'pre-wrap', minHeight: '90px', fontSize: '10.5pt' }}>
          {compRecord['task4_feedback']}
        </div>
      </div>

      <div style={{ textAlign: 'center', marginBottom: '20px', fontWeight: 'bold', fontSize: '12.5pt' }}>
        Result:{' '}
        <span
          className={`relative inline-block mx-2 ${isStudent ? '' : 'cursor-pointer'}`}
          onClick={() => { if (!isStudent) setCompRecord({ ...compRecord, 'task4_result': 'S' }) }}
          style={{ padding: '4px' }}
        >
          Satisfactory (S)
          {compRecord['task4_result'] === 'S' && (
            <span style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', border: '2px solid red', borderRadius: '50%', width: '110%', height: '140%', pointerEvents: 'none' }}></span>
          )}
        </span>
        <span style={{ margin: '0 8px' }}>/</span>
        <span
          className={`relative inline-block mx-2 ${isStudent ? '' : 'cursor-pointer'}`}
          onClick={() => { if (!isStudent) setCompRecord({ ...compRecord, 'task4_result': 'NS' }) }}
          style={{ padding: '4px' }}
        >
          Not Satisfactory (NS)
          {compRecord['task4_result'] === 'NS' && (
            <span style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', border: '2px solid red', borderRadius: '50%', width: '110%', height: '140%', pointerEvents: 'none' }}></span>
          )}
        </span>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse', border: '1.5px solid black' }}>
        <tbody>
          <tr>
            <td style={{ width: '60%', borderRight: '1.5px solid black', padding: '8px', verticalAlign: 'top' }}>
              <p style={{ margin: 0, lineHeight: '1.4', fontSize: '10pt' }}><span style={{ fontWeight: 'bold' }}>Assessor:</span> I declare that I have conducted a fair, valid, reliable and flexible assessment with this student, and I have provided appropriate feedback.</p>
            </td>
            <td style={{ width: '40%', padding: '8px 12px', position: 'relative', fontSize: '10pt' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', height: '100%', justifyContent: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Signature:</span>
                  <div
                    className="no-print"
                    onClick={() => openSigModal('assessor_signature', 'comp')}
                    style={{ borderBottom: '1.5px solid black', flex: 1, minHeight: '24px', cursor: isStudent ? 'default' : 'pointer', position: 'relative' }}
                  >
                    {compRecord.assessor_signature ? (
                      <img src={compRecord.assessor_signature} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    ) : (
                      <span style={{ fontSize: '9px', color: '#888' }}>{isStudent ? '' : 'Click to sign'}</span>
                    )}
                  </div>
                  <div className="hidden print:block" style={{ borderBottom: '1.5px solid black', flex: 1, height: '20px', position: 'relative' }}>
                    {compRecord.assessor_signature && (
                      <img src={compRecord.assessor_signature} alt="Sig" style={{ height: '35px', position: 'absolute', bottom: '-4px', mixBlendMode: 'multiply' }} />
                    )}
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <span>Date:</span>
                  <span className="no-print" style={{ borderBottom: '1.5px solid black', flex: 1, display: 'inline-block', height: '24px', position: 'relative' }}>
                    <input
                      type="date"
                      style={{ width: '100%', height: '100%', outline: 'none', border: 'none', background: 'transparent', fontFamily: "'Times New Roman', serif", fontSize: '10pt', margin: 0, padding: '0 0 0 4px', cursor: isStudent ? 'default' : 'pointer' }}
                      value={compRecord.assessment_date || ''}
                      onChange={(e) => { if (!isStudent) setCompRecord({ ...compRecord, assessment_date: e.target.value }) }}
                      readOnly={isStudent}
                    />
                  </span>
                  <span className="hidden print:inline-block" style={{ borderBottom: '1.5px solid black', flex: 1, height: '20px', paddingLeft: '4px' }}>
                    {compRecord.assessment_date ? formatDisplayDate(compRecord.assessment_date) : ''}
                  </span>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  
  <PageFooter n={27} />
</div>
